'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Deliveryschedule
    
    Public Class DLVR_SCH_Form_RightClick
        Inherits B1Event

        Public Sub New()
            MyBase.New()
        End Sub

        <B1Listener(BoEventTypes.et_RIGHT_CLICK, True, {"DLVRSCHv2"})>
        Public Overridable Function OnBeforeRightClick(ByVal pVal As ContextMenuInfo) As Boolean
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            'ADD YOUR ACTION CODE HERE ...
            Dim docentry As String = form.Items.Item("DocEntry").Specific.value
            'Dim a As String = docentry
            If docentry <> "" Then
                Glovar._docentryds = docentry
            End If
            Return True
        End Function

        <B1Listener(BoEventTypes.et_KEY_DOWN, False, {"DLVRSCHv2"})>
        Public Overridable Sub OnAfterKeyDown(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim mangulanmbmatrix As Matrix = CType(form.Items.Item("mtx_ds").Specific, Matrix)
            'ADD YOUR ACTION CODE HERE ...
            Try
                If pVal.ItemUID = "Truck" Then
                    Dim truck As String = form.Items.Item("Truck").Specific.value
                    Dim trucktype As String = Control._retRstField("select ""U_IDU_TRUCK_TYPE"" from ""@IDU_TRUCK"" where ""Code""= '" & truck & "'")
                    Dim truckcapacity As Double = CDbl(Control._retRstField("select ""U_IDU_DEFAULT_WEIGHT"" from ""@IDU_TRUCK"" where ""Code""='" & truck & "'"))

                    If trucktype = "Other" Then
                        form.Items.Item("truckqty").Enabled = True
                    Else
                        form.Items.Item("truckqty").Enabled = False
                    End If

                    form.Items.Item("truckqty").Specific.value = truckcapacity
                End If
            Catch ex As Exception
                B1Connections.theAppl.MessageBox("KeyDown|OnAfterKeyDown|" & ex.Message.ToString)
            End Try

        End Sub

        <B1Listener(BoEventTypes.et_FORM_DATA_ADD, False, {"DLVRSCHv2"})>
        Public Overridable Sub OnAfterFormDataAdd(ByVal pVal As BusinessObjectInfo)
            Try
                Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
                Dim docentry As String = form.DataSources.DBDataSources.Item("@ODLS").GetValue("DocEntry", 0)

                Dim data As Recordset
                Dim oDoc As SAPbobsCOM.Documents = Nothing
                oDoc = B1Connections.diCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.oQuotations)

                Dim sql As String = "select * from ""@DLS1"" where ""DocEntry""=" & docentry
                data = Control._recordSet(sql)

                While data.EoF = False
                    Dim pientry As String = data.Fields.Item("U_IDU_PIEntry").Value
                    Dim balance As Double = CDbl(Control._retRstField("SELECT SUM(T1.""U_IDU_PI_Bal"") FROM ""OQUT"" T0 INNER JOIN ""QUT1"" T1 ON T0.""DocEntry""=T1.""DocEntry"" where T0.""DocEntry""=" & pientry))

                    If balance = 0 Then
                        oDoc.GetByKey(CInt(pientry))
                        oDoc.Close()
                    End If
                    data.MoveNext()
                End While

                Control._formStatus(form)

            Catch ex As Exception
                B1Connections.theAppl.MessageBox("Form_FORM_DATA_ADD_DS|OnAfterFormDataAddDS|" & ex.Message.ToString)
            Finally

            End Try
        End Sub

        <B1Listener(BoEventTypes.et_FORM_DATA_LOAD, False, {"DLVRSCHv2"})>
        Public Overridable Sub OnAfterFormDataLoad(ByVal pVal As BusinessObjectInfo)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            'ADD YOUR ACTION CODE HERE ...
            Dim oRecordSet As Recordset = B1Connections.diCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.BoRecordset)
            oRecordSet.DoQuery("SELECT T0.""CODE"" FROM ""RTYP"" T0 WHERE T0.""MNU_ID"" ='DLVR_SCH'")
            form.ReportType = oRecordSet.Fields.Item(0).Value
            Control._formStatus(form)
        End Sub

        '<B1Listener(BoEventTypes.et_PRINT_LAYOUT_KEY, False, {"DLVRSCHv2"})>
        <B1Listener(BoEventTypes.et_PRINT_LAYOUT_KEY, True, {"DLVRSCHv2"})>
        Public Overridable Function OnBeforePrintLayOutKey(ByVal eventInfo As LayoutKeyInfo) As Boolean
            Dim form As Form = B1Connections.theAppl.Forms.Item(eventInfo.FormUID)

            Dim oEntry As Item = form.Items.Item("DocEntry")
            eventInfo.LayoutKey = oEntry.Specific.value

            Return True
        End Function
    End Class
End Namespace
