'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Deliveryschedule
    
    Public Class CFL_Cuscode
        Inherits B1Item

        Public Sub New()
            MyBase.New()
            FormType = "DLVRSCHv2"
            ItemUID = "CustCode"
        End Sub

        <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, True)>
        Public Overridable Function OnBeforeChooseFromList(ByVal pVal As ItemEvent) As Boolean
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("CustCode")
            Dim edittext As EditText = CType(item.Specific, EditText)
            'ADD YOUR ACTION CODE HERE ...

            Control._beforeChooseFromCustomer(form, pVal)

            Return True
        End Function

        <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, False)> _
        Public Overridable Sub OnAfterChooseFromList(ByVal pVal As ItemEvent)
            Try
                If pVal.FormMode = BoFormMode.fm_FIND_MODE Then
                    Exit Sub
                End If
                Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID.ToString)
                Dim dt As DataTable
                Dim i As Integer
                dt = pVal.SelectedObjects
                If dt Is Nothing = False Then
                    If dt.Rows.Count > 0 Then
                        With form.DataSources.DBDataSources.Item("@ODLS")
                            For i = 0 To dt.Rows.Count - 1
                                .SetValue("U_IDU_CardCode", 0, dt.Columns.Item("CardCode").Cells.Item(i).Value)
                                .SetValue("U_IDU_CardName", 0, dt.Columns.Item("CardName").Cells.Item(i).Value)
                            Next
                        End With
                        If form.Mode = BoFormMode.fm_OK_MODE Then
                            form.Mode = BoFormMode.fm_UPDATE_MODE
                        End If
                    End If
                End If
            Catch ex As Exception
                B1Connections.theAppl.MessageBox("Setting_CFL_CusCode|OnAfterChooseFromList|" & ex.Message.ToString)
            End Try
        End Sub

    End Class
End Namespace
