'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM
Public Class DLVR_SCH__Button__btnSO
    Inherits B1Item

    Public Sub New()
        MyBase.New()
        FormType = "DLVRSCHv2"
        ItemUID = "btnSO"
    End Sub

    <B1Listener(BoEventTypes.et_ITEM_PRESSED, False)>
    Public Overridable Sub OnAfterItemPressed(ByVal pVal As ItemEvent)
        Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        Dim mtx As SAPbouiCOM.Matrix = form.Items.Item("mtx_ds").Specific
        'ADD YOUR ACTION CODE HERE ...
        'Dim oDoc As SAPbobsCOM.Documents = Nothing
        'oDoc = B1Connections.diCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.oDrafts)
        'Dim lRetCode As Integer
        'Dim errorCode As Integer
        'Dim errorMessage As String = ""

        Dim cuscode As String = form.Items.Item("CustCode").Specific.value
        Dim dsno As String = form.Items.Item("DocNum").Specific.value
        Dim docentry As String = form.Items.Item("DocEntry").Specific.Value
        'Dim cusname As String = form.Items.Item("CustName").Specific.value
        'Dim sodate As Date = Date.ParseExact(form.Items.Item("SoDate").Specific.Value, "yyyyMMdd", Globalization.CultureInfo.InvariantCulture)
        'Dim grandtotal As Double = CDbl(form.Items.Item("Grtotal").Specific.value)

        Try
            Dim formActive As SAPbouiCOM.Form
            Dim formActiveUdf As SAPbouiCOM.Form
            Dim mtxso As SAPbouiCOM.Matrix

            B1Connections.theAppl.ActivateMenuItem("2050") 'Settlement
            formActive = B1Connections.theAppl.Forms.Item(B1Connections.theAppl.Forms.ActiveForm.UniqueID.ToString)
            formActiveUdf = B1Connections.theAppl.Forms.Item(formActive.UDFFormUID)
            mtxso = formActive.Items.Item("38").Specific

            Glovar._formaddon = form

            formActive.Items.Item("4").Specific.Value = cuscode
            formActive.Items.Item("10").Specific.Value = form.Items.Item("SoDate").Specific.Value
            formActive.Items.Item("46").Specific.Value = form.Items.Item("SoDate").Specific.Value
            Dim tes As String = "Base On D/S No. " & dsno.ToString
            formActive.Items.Item("16").Specific.Value = tes.ToString

            formActiveUdf.Items.Item("U_IDU_DSNo").Specific.Value = docentry.ToString
            'CType(formActive.Items.Item("U_IDU_DSNo").Specific, EditText).Value = docentry.ToString
            'formActive.DataSources.DBDataSources.Item("ORDR").SetValue("14", 0, docentry.ToString)
            'formActive.DataSources.DBDataSources.Item("ORDR").GetValue("U_IDU_DSNo", 0)
            'formActive.Items.
            'With formActive.DataSources.DBDataSources.Item("@ORDR")
            '    .SetValue("U_IDU_DSNo", 0, docentry.ToString)
            'End With

            For i = 1 To mtx.RowCount
                mtxso.AddRow(1, mtxso.RowCount)
                'Dim tes As String = mtx.Columns.Item("ItemCod").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("1").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("ItemCod").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("14").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("Price").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("11").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("Qty").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("U_Packaging").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("Pckg").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("U_IDU_Bags").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("QtyBgs").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("U_Grade").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("grade").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("24").Cells.Item(i).Specific, EditText).Value = "01"
                CType(mtxso.Columns.Item("2004").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("OcrCode").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("2003").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("OcrCode2").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("2002").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("OcrCode3").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("2001").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("OcrCode4").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("2000").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("OcrCode5").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("U_IDU_PrdctHrchy").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("PrdcHrchy").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("31").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("Prjct").Cells.Item(i).Specific.Value
                CType(mtxso.Columns.Item("U_IDU_PricingGrp").Cells.Item(i).Specific, ComboBox).Select(mtx.Columns.Item("PrcGrp").Cells.Item(i).Specific.Value, SAPbouiCOM.BoSearchKey.psk_ByValue)
                CType(mtxso.Columns.Item("18").Cells.Item(i).Specific, ComboBox).Select(mtx.Columns.Item("VatGrp").Cells.Item(i).Specific.Value, SAPbouiCOM.BoSearchKey.psk_ByValue)
                CType(mtxso.Columns.Item("U_IDU_RefPI_No").Cells.Item(i).Specific, EditText).Value = mtx.Columns.Item("PtNo").Cells.Item(i).Specific.Value 'update 04/06/2024

            Next



            'Doc_Realisasi.PrepareForm(formActive)



            'oDoc.CardCode = cuscode
            'oDoc.CardName = cusname
            'oDoc.DocDate = sodate
            'oDoc.DocDueDate = sodate
            'Dim tes As String = "Base On D/S No. " & dsno.ToString
            'oDoc.Comments = tes.ToString

            'For i = 1 To mtx.RowCount
            '    oDoc.Lines.ItemCode = mtx.Columns.Item("ItemCod").Cells.Item(i).Specific.Value
            '    oDoc.Lines.ItemDescription = mtx.Columns.Item("ItemDes").Cells.Item(i).Specific.Value
            '    oDoc.Lines.UnitPrice = mtx.Columns.Item("Price").Cells.Item(i).Specific.Value
            '    oDoc.Lines.Quantity = mtx.Columns.Item("Qty").Cells.Item(i).Specific.Value
            '    oDoc.Lines.UserFields.Fields.Item("U_Packaging").Value = mtx.Columns.Item("Pckg").Cells.Item(i).Specific.Value
            '    oDoc.Lines.UserFields.Fields.Item("U_IDU_Bags").Value = mtx.Columns.Item("QtyBgs").Cells.Item(i).Specific.Value
            '    'oDoc.Lines.LineTotal = mtx.Columns.Item("TtlAmnt").Cells.Item(i).Specific.Value
            '    oDoc.Lines.Add()
            'Next

            ''oDoc.DocTotal = grandtotal


            ''lRetCode = oDoc.Add()

            'If lRetCode = 0 Then
            '    Dim sonum As String = B1Connections.diCompany.GetNewObjectKey()

            '    With form.DataSources.DBDataSources.Item("@ODLS")
            '        .SetValue("U_IDU_SO_Number", 0, sonum)
            '    End With

            '    'Dim docentry As String = form.Items.Item("DocEntry").Specific.Value

            '    'Control._executeQuery("update ""@ODLS"" set ""U_IDU_DocStatus""='C'  where ""DocEntry""=" & docentry)

            '    Dim status As ComboBox = CType(form.Items.Item("DocStatus").Specific, ComboBox)
            '    status.Select("C", BoSearchKey.psk_ByValue)

            '    form.Mode = BoFormMode.fm_UPDATE_MODE
            '    form.Items.Item("1").Click(BoCellClickType.ct_Regular)

            '    Control._formStatus(form)
            'Else
            '    B1Connections.diCompany.GetLastError(errorCode, errorMessage)
            '    Throw New Exception("Error Code : " + errorCode.ToString + " | " + "Error Message : " + errorMessage)
            'End If

        Catch ex As Exception
            B1Connections.theAppl.MessageBox("btnSO|OnAfterItemPressed|" & ex.Message.ToString)
        End Try
    End Sub



    <B1Listener(BoEventTypes.et_ITEM_PRESSED, True)> _
    Public Overridable Function OnBeforeItemPressed(ByVal pVal As ItemEvent) As Boolean
        Try
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As SAPbouiCOM.Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)

            Dim sodate As String = form.Items.Item("SoDate").Specific.value
            Dim postdate As String = form.Items.Item("PostDate").Specific.value
            Dim sonum As String = form.Items.Item("sonum").Specific.value
            Dim draftnum As String = form.Items.Item("drnum").Specific.value

            If sodate = "" Then
                B1Connections.theAppl.MessageBox("SO Date cannot be empty")
                Return False
            End If

            If sodate < postdate Then
                B1Connections.theAppl.MessageBox("SO Date must be greater than Post Date")
                Return False
            End If

            If sonum <> "" Or draftnum <> "" Then
                B1Connections.theAppl.MessageBox("SO or Draft has been created")
                Return False
            End If

            If Not form.Mode = BoFormMode.fm_OK_MODE Then
                B1Connections.theAppl.MessageBox("Please update Form first")
                Return False
            End If


            Return True
        Catch ex As Exception
            B1Connections.theAppl.MessageBox("Button1|OnBeforeItemPressed|" & ex.Message.ToString)
        End Try
    End Function
End Class
