'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM
Public Class DLVR_SCH__EditText__SoDate
    Inherits B1Item

    Public Sub New()
        MyBase.New()
        FormType = "DLVRSCHv2"
        ItemUID = "SoDate"
    End Sub

    <B1Listener(BoEventTypes.et_VALIDATE, False)> _
    Public Overridable Sub OnAfterValidate(ByVal pVal As ItemEvent)
        Try
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As SAPbouiCOM.Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)


            If form.Mode <> BoFormMode.fm_ADD_MODE Then
                'Control._formStatus(form)

                form.Items.Item("CustCode").Enabled = False
                form.Items.Item("CustName").Enabled = False
                form.Items.Item("DelTerm").Enabled = False
                form.Items.Item("Transptr").Enabled = False
                form.Items.Item("Truck").Enabled = False
                form.Items.Item("truckqty").Enabled = False
                form.Items.Item("DocNum").Enabled = False
                form.Items.Item("PostDate").Enabled = False
                form.Items.Item("mtx_ds").Enabled = False
            End If

        Catch ex As Exception
            B1Connections.theAppl.MessageBox("VALIDATE_SoDate|OnAfterValidate|" & ex.Message.ToString)
        End Try
    End Sub
End Class
