'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Deliveryschedule

    Public Class DLVR_SCH__ComboBox__Series
        Inherits B1Item

        Public Sub New()
            MyBase.New()
            FormType = "DLVRSCHv2"
            ItemUID = "Series"
        End Sub

        <B1Listener(BoEventTypes.et_COMBO_SELECT, False)>
        Public Overridable Sub OnAfterComboSelect(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim oForm As SAPbouiCOM.Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)

            Try
                If oForm.Mode <> BoFormMode.fm_FIND_MODE Then
                    Dim series As ComboBox = CType(oForm.Items.Item("Series").Specific, ComboBox)
                    Control._setDocumentNumber("DocNum", oForm, series.Selected.Value)
                End If
            Catch ex As Exception
                B1Connections.theAppl.MessageBox(ex.Message.ToString)
            End Try
        End Sub

    End Class
End Namespace
