'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

'Option Strict Off
'Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM
Public Class DLVR_SCH__EditText__PostingDate
    Inherits B1Item

    Public Sub New()
        MyBase.New()
        FormType = "DLVRSCHv2"
        ItemUID = "PostDate"
    End Sub

    '<B1Listener(BoEventTypes.et_LOST_FOCUS, False)>
    <B1Listener(BoEventTypes.et_LOST_FOCUS, False)>
    Public Overridable Sub OnAfterLostFocus(ByVal pVal As ItemEvent)
        Dim postdate As Date = Nothing

        Try
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As SAPbouiCOM.Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim mtx_ds As SAPbouiCOM.Matrix = form.Items.Item("mtx_ds").Specific
            Dim cuscode As String = form.Items.Item("CustCode").Specific.value
            ' update 04/06/2024
            Dim filterPI As String = form.Items.Item("FilterPI").Specific.value
            Dim filterGrd As String = form.Items.Item("FilterGrd").Specific.value

            If form.Mode <> BoFormMode.fm_ADD_MODE Then
                Control._formStatus(form)
            End If

            Control._setSeries("Series", form, Nothing)

            If form.Items.Item("PostDate").Specific.Value = "" Then
                B1Connections.theAppl.MessageBox("Post Date cannot be empty")
                Exit Sub
            End If

            If cuscode = "" Then
                B1Connections.theAppl.MessageBox("Customer code cannot be empty")
                Exit Sub
            End If

            postdate = Date.ParseExact(form.Items.Item("PostDate").Specific.Value, "yyyyMMdd", Globalization.CultureInfo.InvariantCulture)

            Dim oRs As Recordset
            Dim sql As String = "CALL  _IDU_DLS_GET_PI('" & cuscode & "','" & postdate.ToString("yyyyMMdd") & "','" & filterPI.ToString() & "','" & filterGrd.ToString() & "')" ' new update
            oRs = Control._recordSet(sql)

            mtx_ds.Clear()

            Do Until oRs.EoF
                mtx_ds.AddRow(1, mtx_ds.RowCount)

                Dim bego As String = oRs.Fields.Item("U_U_IDU_Bagging_Weight").Value
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "PIEntry", oRs.Fields.Item("DocEntry").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "PtNo", oRs.Fields.Item("DocNum").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "CusRef", oRs.Fields.Item("NumAtCard").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "ItemCod", oRs.Fields.Item("ItemCode").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "ItemDes", oRs.Fields.Item("Dscription").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "Price", oRs.Fields.Item("Price").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "Qty", oRs.Fields.Item("Qty").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "BlncQty", oRs.Fields.Item("U_IDU_PI_Bal").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "Uom", oRs.Fields.Item("unitMsr").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "Whs", oRs.Fields.Item("WhsCode").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "TtlAmnt", oRs.Fields.Item("TotalAmount").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "QtyBgs", oRs.Fields.Item("U_IDU_Bags").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "BagWgt", bego.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "Pckg", oRs.Fields.Item("U_Packaging").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "QtyPI", oRs.Fields.Item("Quantity").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "PrdcHrchy", oRs.Fields.Item("U_IDU_PrdctHrchy").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "PrcGrp", oRs.Fields.Item("U_IDU_PricingGrp").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "grade", oRs.Fields.Item("U_Grade").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "Prjct", oRs.Fields.Item("Project").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "OcrCode", oRs.Fields.Item("OcrCode").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "OcrCode2", oRs.Fields.Item("OcrCode2").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "OcrCode3", oRs.Fields.Item("OcrCode3").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "OcrCode4", oRs.Fields.Item("OcrCode4").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "OcrCode5", oRs.Fields.Item("OcrCode5").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "GroupNum", oRs.Fields.Item("GroupNum").Value.ToString)
                mtx_ds.SetCellWithoutValidation(mtx_ds.RowCount, "VatGrp", oRs.Fields.Item("VatGroup").Value.ToString)
                oRs.MoveNext()
            Loop
        Catch ex As Exception
            B1Connections.theAppl.MessageBox("VALIDATE_PostDate|OnAfterValidate|" & ex.Message.ToString)
        End Try
    End Sub
End Class