//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1PostingDataText.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryGet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryGet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("B1PostingDataText.Properties.QueryGet", typeof(QueryGet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 
        ///	ISNULL(B.&quot;CardCode&quot;,&apos;&apos;)			As &quot;CardCode&quot;,
        ///	ISNULL(B.&quot;Address&quot;,&apos;&apos;)			As &quot;AddressID&quot;,
        ///	ISNULL(B.&quot;AdresType&quot;,&apos;&apos;)		As &quot;AdresType&quot;,
        ///	ISNULL(B.&quot;Street&quot;,&apos;&apos;)			As &quot;Street&quot;
        ///From OCRD A
        ///JOIN CRD1 B ON B.&quot;CardCode&quot;=A.&quot;CardCode&quot;
        ///Where A.&quot;CardType&quot;=&apos;C&apos; AND
        ///A.&quot;validFor&quot;=&apos;Y&apos;
        ///AND B.&quot;AdresType&quot;=&apos;S&apos;.
        /// </summary>
        internal static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 
        ///	A.&quot;CardCode&quot;						As &quot;CardCode&quot;,
        ///	ISNULL(A.&quot;CardName&quot;,&apos;&apos;)				As &quot;CardName&quot;,
        ///	ISNULL(B.&quot;GroupName&quot;,&apos;&apos;)			As &quot;CustomerGroup&quot;,
        ///	C.&quot;GroupNum&quot;			 			As &quot;TOPCode&quot;,
        ///	ISNULL(C.&quot;PymntGroup&quot;,&apos;&apos;) 			As &quot;TOP&quot;,
        ///	ISNULL(A.&quot;CreditLine&quot;,0) 			As &quot;CreditLimit&quot;,
        ///	ISNULL(D.&quot;ListName&quot;,&apos;&apos;) 			As &quot;PriceList&quot;,
        ///	ISNULL(A.&quot;AddID&quot;,&apos;&apos;) 				As &quot;OldCode&quot;,
        ///	ISNULL(A.&quot;SlpCode&quot;,&apos;-1&apos;)				As &quot;SlpCode&quot;
        ///From OCRD A	
        ///LEFT JOIN OCRG B ON B.&quot;GroupCode&quot;=A.&quot;GroupCode&quot;
        ///LEFT JOIN OCTG C ON C.&quot;GroupNum&quot;=A.&quot;GroupNum&quot;
        ///LEFT JOIN OP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerHeader {
            get {
                return ResourceManager.GetString("CustomerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	A.&quot;CardCode&quot; As &quot;CardCode&quot;,
        ///	ISNULL(A.&quot;CardName&quot;,&apos;&apos;) As &quot;CardName&quot;,
        ///	ISNULL(A.&quot;U_IDU_Lv1&quot;,&apos;&apos;) As &quot;U_IDU_Lv1&quot;,
        ///	ISNULL(A.&quot;U_IDU_Lv2&quot;,&apos;&apos;) As &quot;U_IDU_Lv2&quot;,
        ///	ISNULL(A.&quot;U_IDU_Lv3&quot;,&apos;&apos;) As &quot;U_IDU_Lv3&quot;,
        ///	ISNULL(A.&quot;U_IDU_Lv4&quot;,&apos;&apos;) As &quot;U_IDU_Lv4&quot;,
        ///	ISNULL(A.&quot;U_IDU_Lv5&quot;,&apos;&apos;) As &quot;U_IDU_Lv5&quot;,
        ///	ISNULL(A.&quot;CntctPrsn&quot;,&apos;&apos;) As &quot;CntctPrsn&quot;,
        ///	ISNULL(A.&quot;Phone1&quot;,&apos;&apos;) As &quot;Phone1&quot;,
        ///	ISNULL(A.&quot;Phone2&quot;,&apos;&apos;) As &quot;Phone2&quot;,
        ///	ISNULL(A.&quot;Address&quot;,&apos;&apos;) As &quot;Address&quot;,
        ///	ISNULL(B.&quot;GroupName&quot;,&apos;&apos;) As &quot;GroupName&quot;,
        ///	ISNULL(A.&quot;CreditLi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDU_GET_Customer {
            get {
                return ResourceManager.GetString("IDU_GET_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE OCRD SET &quot;U_is_post&quot; = &apos;Y&apos; WHERE &quot;U_is_post&quot; = &apos;N&apos;.
        /// </summary>
        internal static string Update_Flag {
            get {
                return ResourceManager.GetString("Update_Flag", resourceCulture);
            }
        }
    }
}
