'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Public Class Menu_1292

    Inherits B1Menu

    Public Sub New()
        MyBase.New()
        MenuUID = "1292"
    End Sub

    '<B1Listener(BoEventTypes.et_MENU_CLICK, False, {"DLVR_SCH"})> _
    'Public Overridable Sub OnAfterMenuClick(ByVal pVal As MenuEvent)
    '    Dim oForm As Form = B1Connections.theAppl.Forms.ActiveForm
    '    Dim frmUID As String = oForm.UniqueID.ToString

    '    Try
    '        'If oForm.TypeEx = "DLVR_SCH" Then
    '        '    Dim oMatrix As Matrix = oForm.Items.Item("mtx_ds").Specific
    '        '    oForm.DataSources.DBDataSources.Item("@DLS1").Clear()
    '        '    oMatrix.AddRow()
    '        'End If

    '    Catch ex As Exception
    '        B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Short, True)
    '    End Try
    'End Sub

End Class
