'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_IDU_DLS_BALANCEDQTY.sql")>  _
        Public Property _IDU_DLS_BALANCEDQTY() As String
            Get
                Return CType(Me("_IDU_DLS_BALANCEDQTY"),String)
            End Get
            Set
                Me("_IDU_DLS_BALANCEDQTY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_IDU_DLS_GET_PI.sql")>  _
        Public Property _IDU_DLS_GET_PI() As String
            Get
                Return CType(Me("_IDU_DLS_GET_PI"),String)
            End Get
            Set
                Me("_IDU_DLS_GET_PI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_IDU_DLS_GET_STOCKWHS.sql")>  _
        Public Property _IDU_DLS_GET_STOCKWHS() As String
            Get
                Return CType(Me("_IDU_DLS_GET_STOCKWHS"),String)
            End Get
            Set
                Me("_IDU_DLS_GET_STOCKWHS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_IDU_DLS_GETDLSBYID.sql")>  _
        Public Property _IDU_DLS_GETDLSBYID() As String
            Get
                Return CType(Me("_IDU_DLS_GETDLSBYID"),String)
            End Get
            Set
                Me("_IDU_DLS_GETDLSBYID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_IDU_DLS_LAYOUTDS.sql")>  _
        Public Property _IDU_DLS_LAYOUTDS() As String
            Get
                Return CType(Me("_IDU_DLS_LAYOUTDS"),String)
            End Get
            Set
                Me("_IDU_DLS_LAYOUTDS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_IDU_DLS_LISTAPPROVAL.sql")>  _
        Public Property _IDU_DLS_LISTAPPROVAL() As String
            Get
                Return CType(Me("_IDU_DLS_LISTAPPROVAL"),String)
            End Get
            Set
                Me("_IDU_DLS_LISTAPPROVAL") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Deliveryschedule.My.MySettings
            Get
                Return Global.Deliveryschedule.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
